wallpaper {
    monitor =
    path = ~/Pictures/wallpapers/L1008514.jpg
    fit_mode = cover # contain|cover|tile|fill
}

# wallpaper {
#     monitor = DP-2
#     path = ~/.config/hypr/wallpapers/wallpaper.png
#     fit_mode = cover
# }
