#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Autostart Programs

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Set wallpaper
# ~/.config/hypr/scripts/wallpaper &

# Apply themes
~/.config/hypr/scripts/gtkthemes &

# Lauch mako
# ~/.config/hypr/scripts/mako &

# Lauch waybar
# ~/.config/hypr/scripts/waybar &

# Start network manager applet
nm-applet --indicator &

# Start mpd
exec mpd &
